version: 2

models:
  - name: fct_find_customer_referee
    description: "584. Find Customer Referee"
    columns:
      - name: name
        description: "The name of the customer"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Will", "Jane", "Bill", "Zack"]
  - name: fct_recyclable_and_low_fat_products
    description: "1757. Recyclable and Low Fat Products dbt model"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 3]
  - name: fct_big_countries
    description: "595. Big Countries"
    columns:
      - name: name
        description: "The name of the country"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Afghanistan", "Algeria"]
  - name: fct_article_views_i
    description: "1148. Article Views I"
    columns:
      - name: id
        description: "The id of the author"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [4, 7]
  - name: fct_invalid_tweets
    description: "1683. Invalid Tweets"
    columns:
      - name: tweet_id
        description: "The id of the tweet"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [2]
  - name: fct_replace_employee_id_with_the_unique_identifier
    description: "1378. Replace Employee ID With The Unique Identifier"
    columns:
      - name: unique_id
        description: "The unique id of the employee"
        tests:
          - accepted_values:
              values: [1, 2, 3, null]
      - name: name
        description: "The name of the employee"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Alice", "Bob", "Meir", "Winston", "Jonathan"]

  - name: fct_product_sales_analysis_i
    description: "1068. Product Sales Analysis I"
    columns:
      - name: product_name
        description: "The name of the product"
        tests:
          - not_null
          - accepted_values:
              values: ["Nokia", "Apple"]
      - name: year
        description: "The year of the sale"
        tests:
          - not_null
          - accepted_values:
              values: [2008, 2009, 2011]
      - name: price
        description: "The price of the product"
        tests:
          - not_null
          - accepted_values:
              values: [5000, 9000]
  - name: fct_customer_not_make_any_transactions
    description: "1581. Customer Who Visited but Did Not Make Any Transactions"
    columns:
      - name: customer_id
        description: "The id of the customer"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [30, 54, 96]
      - name: count_no_trans
        description: "The number of transactions"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2]

  - name: fct_rising_temperature
    description: "197. Rising Temperature"
    columns:
      - name: id
        description: "The id of the weather"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [2, 4]
  - name: fct_average_time_of_process_per_machine
    description: "1661. Average Time of Process per Machine"
    columns:
      - name: machine_id
        description: "The id of the machine"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [0, 1, 2]
      - name: processing_time
        description: "The processing time"
        tests:
          - not_null
          - accepted_values:
              values: [0.894, 0.995, 1.456]
  - name: fct_employee_bonus
    description: "577. Employee Bonus"
    columns:
      - name: name
        description: "The name of the employee"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Brad", "John", "Dan"]

      - name: bonus
        description: "The bonus of the employee"
        tests:
          - accepted_values:
              values: [null, 500]
  - name: fct_students_and_examinations
    description: "1280. Students and Examinations"
    columns:
      - name: subject_name
        description: "The name of the subject"
        tests:
          - not_null
          - accepted_values:
              values: ["Math", "Physics", "Programming"]
      - name: attended_exams
        description: "The number of exams attended by the student"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1, 2, 3]
  - name: fct_managers_with_at_least_5_direct_reports
    description: "570. Managers with at Least 5 Direct Reports"
    columns:
      - name: name
        description: "The name of the manager"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["John"]
  - name: fct_confirmation_rate
    description: "1934. Confirmation Rate"
    columns:
      - name: user_id
        description: "The id of the user"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [2, 3, 6, 7]
      - name: confirmation_rate
        description: "The confirmation rate"
        tests:
          - not_null
          - accepted_values:
              values: [0.00, 0.50, 1.00]
  - name: fct_not_boring_movies
    description: "620. Not Boring Movies"
    columns:
      - name: id
        description: "The id of the movie"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 5]
  - name: fct_average_selling_price
    description: "1251. Average Selling Price"
    columns:
      - name: product_id
        description: "The id of the product"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 2]
      - name: average_price
        description: "The average price of the product"
        tests:
          - not_null
          - accepted_values:
              values: [6.96, 16.96]
  - name: fct_project_employees_i
    description: "1075. Project Employees I"
    columns:
      - name: project_id
        description: "The id of the project"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 2]
      - name: average_years
        description: "The average years of the employees"
        tests:
          - not_null
          - accepted_values:
              values: [2.00, 2.50]
  - name: fct_percentage_of_users_attended_a_contest
    description: "1633. Percentage of Users Attended a Contest"
    columns:
      - name: contest_id
        description: "The id of the contest"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [208, 209, 210, 215, 207]
      - name: percentage
        description: "The percentage of users attended a contest"
        tests:
          - not_null
          - accepted_values:
              values: [100.0, 66.67, 33.33]
  - name: fct_queries_quality_and_percentage
    description: "1211. Queries Quality and Percentage"
    columns:
      - name: query_name
        description: "The name of the query"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Dog", "Cat"]
      - name: quality
        description: "The quality of the query"
        tests:
          - not_null
          - accepted_values:
              values: [2.50, 0.66]
      - name: poor_query_percentage
        description: "The percentage of poor queries"
        tests:
          - not_null
          - accepted_values:
              values: [33.33]
