version: 2

models:
  - name: fct_recyclable_and_low_fat_products
    description: "1757. Recyclable and Low Fat Products dbt model"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 3]
