Create table If Not Exists lc1075_Project (project_id int, employee_id int);
Create table If Not Exists lc1075_Employee (employee_id int, name varchar(10), experience_years int);
Truncate table lc1075_Project;
insert into lc1075_Project (project_id, employee_id) values ('1', '1');
insert into lc1075_Project (project_id, employee_id) values ('1', '2');
insert into lc1075_Project (project_id, employee_id) values ('1', '3');
insert into lc1075_Project (project_id, employee_id) values ('2', '1');
insert into lc1075_Project (project_id, employee_id) values ('2', '4');
Truncate table lc1075_Employee;
insert into lc1075_Employee (employee_id, name, experience_years) values ('1', 'Khaled', '3');
insert into lc1075_Employee (employee_id, name, experience_years) values ('2', 'Ali', '2');
insert into lc1075_Employee (employee_id, name, experience_years) values ('3', 'John', '1');
insert into lc1075_Employee (employee_id, name, experience_years) values ('4', 'Doe', '2');
